{"description": "### Impact\nSome internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like user email address in staff-authenticated requests.\n\nThis issue has been patched in versions 3.1.48, 3.7.59, 3.8.30, 3.9.27, 3.10.14 and 3.11.12.\n\n### Workarounds\nNone\n\n### For more information\nIf you have any questions or comments about this advisory:\n* Open a discussion at https://github.com/saleor/saleor/discussions\n* Email us at [hello@saleor.io](mailto:hello@saleor.io)\n", "methods": ["Information Disclosure via API error messages.", "Exposure of sensitive information via API error messages (user email address).", "Unhandled Python exceptions returned as error messages."]}