{"description": "### Impact\nThe implementation of [`tf.raw_ops.StagePeek`](https://github.com/tensorflow/tensorflow/blob/f3b9bf4c3c0597563b289c0512e98d4ce81f886e/tensorflow/core/kernels/stage_op.cc#L261) does not fully validate the input arguments. This results in a `CHECK`-failure which can be used to trigger a denial of service attack:\n\n```python\nimport tensorflow as tf\n\nindex = tf.constant([], shape=[0], dtype=tf.int32)\ntf.raw_ops.StagePeek(index=index, dtypes=[tf.int32])\n```\n  \nThe code assumes `index` is a scalar but there is no validation for this before accessing its value:\n  \n```cc\nstd::size_t index = ctx->input(0).scalar<int>()();\n``` \n\n### Patches\nWe have patched the issue in GitHub commit [cebe3c45d76357d201c65bdbbf0dbe6e8a63bbdb](https://github.com/tensorflow/tensorflow/commit/cebe3c45d76357d201c65bdbbf0dbe6e8a63bbdb).\n\nThe fix will be included in TensorFlow 2.9.0. We will also cherrypick this commit on TensorFlow 2.8.1, TensorFlow 2.7.2, and TensorFlow 2.6.4, as these are also affected and still in supported range.\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n### Attribution\nThis vulnerability has been reported by Neophytos Christou from Secure Systems Lab at Brown University.", "methods": ["Missing validation causes denial of service via `StagePeek`.", "Trigger a denial of service attack by exploiting a CHECK-failure.", "No validation for input arguments before accessing their value."]}