{"description": "URL GET parameter \"logtime\" utilized within the \"downloadlog\" function from \"cbpi/http_endpoints/http_system.py\" is subsequently passed to the \"os.system\" function in \"cbpi/controller/system_controller.py\" without prior validation allowing arbitrary code execution. This issue affects CraftBeerPi 4: from 4.0.0.58 (commit 563fae9) before 4.4.1.a1 (commit 57572c7).\n\n", "methods": ["Utilized an insecure direct object reference in the \"logtime\" URL GET parameter.", "Executed arbitrary code via the \"os.system\" function.", "Failed to validate user input before passing it to the \"os.system\" function."]}